### PR TITLE
Update Template 

### PR DESCRIPTION
**Pull request by kartikcho**
Added 2 new components to display comparison data,

image

image

 Also, added a basic footer that uses custom graphics for the fellowship logo,

image

Will open a follow up PR soon with individual React components.

### CODE REVIEW

**Comment by IamCathal** [comment]
I was unable to get a query through the graphQL api that got the members of someone's team so we can't get their PRs or any of their stats apart from the actual person we're searching for

**Comment by IamCathal** [comment]
Also maybe comparing yourself to others wouldn't be the best thing if you aren't better than them

**Comment by kartikcho** [comment]
It's not a competition so I'm not sure how this would be perceived by the end user but we could come up with another tracker to use in place of it. Do you have any ideas @IamCathal @sebastiancrossa @gmelodie ?

**Comment by gmelodie** [comment]
Yeah same, I think comparing wouldn't be the best experience, especially if you have less PRs merged than your pod mates (which we all know doesn't say anything about how much work you actually did).

**Pull request merged**
